name: Build and Push Docker Images

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches:
      - main
  push:
    branches:
      - main

env:
  DOCKER_REGISTRY: ghcr.io
  DOCKER_USERNAME: ${{ github.repository_owner }}
  DOCKER_PASSWORD: ${{ secrets.CR_PAT }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker registry
        run: echo $DOCKER_PASSWORD | docker login $DOCKER_REGISTRY -u $DOCKER_USERNAME --password-stdin

      - name: Build and tag Docker images

        run: |
          docker-compose build
          docker push ghcr.io/group12-inpeace/authentication-service:latest
          docker push ghcr.io/group12-inpeace/places-service:latest
          docker push ghcr.io/group12-inpeace/community-service:latest
          docker push ghcr.io/group12-inpeace/map-service:latest
          docker push ghcr.io/group12-inpeace/busyness-service:latest
          docker push ghcr.io/group12-inpeace/api-gateway:latest
          docker push ghcr.io/group12-inpeace/front-end:latest
